[package]
name        = "auction-package"
version     = { workspace = true }
edition     = { workspace = true }
authors     = ["Art3miX <r3mix.il@gmail.com>"]
description = "Package for auction system contracts"
license     = { workspace = true }

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std    = { workspace = true }
cw-storage-plus = { workspace = true }
thiserror       = { workspace = true }
serde           = { workspace = true }
